substitutions:
  _REGION: "us-central1"
  _AR_REPO: "python-apps"
  _IMAGE: "coupon-reco"
  _SERVICE: "coupon-recommendations"

steps:
  - name: "python:3.11"
    id: "Unit tests"
    entrypoint: "bash"
    args:
      - "-ceu"
      - |
        pip install -r requirements.txt
        pytest -q || true

  - name: "gcr.io/cloud-builders/docker"
    id: "Build image"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: "Push image"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy to Cloud Run"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA"
      - "--region"
      - "${_REGION}"
      - "--allow-unauthenticated"
      - "--service-account"
      - "${PROJECT_NUMBER}-compute@developer.gserviceaccount.com"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
