substitutions:
  _REGION: us-central1
  _SERVICE: coupon-recommendations
  _AR_REPO: ml-services
  _MODEL_URI: artifacts/xgboost_coupon_recommendation.pkl
  _IMAGE: '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}'

steps:
# 1) Run unit tests
- name: 'python:3.10-slim'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt
      pip install --no-cache-dir .
      python -m pytest -q

# 2) Build container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE}:${SHORT_SHA}', '.']

# 3) Push to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE}:${SHORT_SHA}']

# 4) Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - '${_SERVICE}'
    - '--image'
    - '${_IMAGE}:${SHORT_SHA}'
    - '--region'
    - '${_REGION}'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'MODEL_URI=${_MODEL_URI}'

images:
- '${_IMAGE}:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
